name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      HF: ${{ secrets.HF }} 
    run: git clone https://huggingface.co/spaces/KunalAIML/demo2# <== Inject the Hugging Face token as an env variable

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          make install

      - name: Lint Check
        run: |
          source .venv/bin/activate
          make lint

      - name: Format Check
        run: |
          source .venv/bin/activate
          make format

      - name: Run Tests
        run: |
          source .venv/bin/activate
          make test

      - name: Hugging Face Auth (Optional)
        if: env.HF != ''
        run: |
          source .venv/bin/activate
          huggingface-cli login --token "$HF"
